server:
  port: 19001
  servlet:
    context-path: /payment

spring:
  application:
    name: cloud-lib-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


