server:
  port: 80

spring:
  application:
    name: cloud-lib-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-lib-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**         # 断言，路径相匹配的进行路由

        - id: order
          uri: lb://cloud-lib-order
          predicates:
            - Path=/order/**

        - id: auth
            uri: lb://cloud-lib-auth
            predicates:
              - Path=/auth/**
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
