server:
  port: 19011
  servlet:
    context-path: /order

spring:
  application:
    name: cloud-lib-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  payment: http://cloud-lib-payment


